language: cpp
sudo: false

env:
  global:
    - PIP=pip

addons:
  apt:
    sources: &sources
      - boost-latest
      - ubuntu-toolchain-r-test
    packages: &packages
      - libboost1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-program-options1.55-dev
      - ninja-build
      - python-virtualenv

cache:
  apt: true

matrix:
  include:
    - compiler: clang
      env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.6
          packages:
            - *packages
            - clang-3.6
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.7
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.7
          packages:
            - *packages
            - clang-3.7
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.8
          packages:
            - *packages
            - clang-3.8
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.9
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.9
          packages:
            - *packages
            - clang-3.9
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *packages
            - clang-4.0
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *packages
            - clang-5.0
            - libstdc++-5-dev

    - compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-5

    - compiler: gcc
      env: COMPILER=g++-6
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-6

    - compiler: gcc
      env: COMPILER=g++-7
      addons: &gcc-7
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-7

    - os: osx
      env: PIP=pip2 COMPILER=clang++ BACKEND=ninja

    # C++17 builds

    - compiler: clang
      env: EXTRAOPTS="--std=c++17" COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *packages
            - clang-5.0
            - libstdc++-7-dev

    - compiler: gcc
      env: EXTRAOPTS="--std=c++17" COMPILER=g++-7
      addons: *gcc-7

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew install ninja
    else
      set -e
      virtualenv env && source env/bin/activate
    fi

  - git clone https://github.com/jimporter/bfg9000.git
  - pushd bfg9000
  - ${PIP} install .
  - popd
install:
  # Build and install the lastest master revision of mettle.
  - git clone https://github.com/jimporter/mettle.git
  - pushd mettle
  - >
    CXX=${COMPILER} CPATH="`pwd`/../include" 9k build --backend=ninja
    --prefix=$HOME
  - cd build
  - ninja install
  - popd
script:
  - >
    CXX=${COMPILER} CXXFLAGS="-Wall -Wextra -pedantic -I$HOME/include"
    LIBRARY_PATH="$HOME/lib" 9k build --backend=ninja
  - cd build
  - ninja test
